=================== IR ===================
(procBegin, main)
(addressOf, r1, i)
(addressOf, r2, p)
(addressOf, r3, j)
(loadWord, r4, r2)
(loadWord, r5, r3)
(addSignedWord, r6, r4, r5)
(storeWord, r1, r6)
(constInt, r7, 0)
(returnWord, r7)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
