=================== IR ===================
(procBegin, main)
(addressOf, r1, i)
(constInt, r2, 0)
(storeWord, r1, r2)
(label, _GeneratedLabel_2)
(addressOf, r3, i)
(constInt, r4, 5)
(loadWord, r5, r3)
(ltSignedWord, r6, r5, r4)
(gotoIfFalse, r6, _GeneratedLabel_3)
(addressOf, r7, i)
(constInt, r8, 3)
(loadWord, r9, r7)
(remSignedWord, r10, r9, r8)
(constInt, r11, 0)
(eqWord, r12, r10, r11)
(gotoIfFalse, r12, _GeneratedLabel_4)
(goto, _GeneratedLabel_3)
(goto, _GeneratedLabel_5)
(label, _GeneratedLabel_4)
(addressOf, r13, i)
(loadWord, r14, r13)
(unaryLogicalNegation, r15, r14)
(label, _GeneratedLabel_5)
(addressOf, r16, i)
(constInt, r17, 99)
(storeWord, r16, r17)
(goto, _GeneratedLabel_2)
(label, _GeneratedLabel_3)
(constInt, r18, 0)
(returnWord, r18)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
