=================== IR ===================
(procBegin, main)
(addressOf, r1, i)
(addressOf, r2, j)
(loadWord, r3, r2)
(castWordToByte, r4, r3)
(castSignedByteToWord, r5, r4)
(storeWord, r1, r5)
(constInt, r6, 0)
(returnWord, r6)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
