=================== IR ===================
(procBegin, main)
(addressOf, r1, i)
(addressOf, r2, j)
(loadWord, r3, r1)
(loadWord, r4, r2)
(multSignedWord, r5, r3, r4)
(storeWord, r1, r5)
(constInt, r6, 0)
(returnWord, r6)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
