=================== IR ===================
(procBegin, main)
(addressOf, r1, i)
(constInt, r2, 5)
(storeWord, r1, r2)
(addressOf, r3, p)
(addressOf, r4, i)
(storeWord, r3, r4)
(addressOf, r5, j)
(addressOf, r6, p)
(loadWord, r7, r6)
(loadWord, r8, r7)
(storeWord, r5, r8)
(constInt, r9, 0)
(returnWord, r9)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
