=================== IR ===================
(procBegin, main)
(addressOf, r1, i)
(loadWord, r2, r1)
(gotoIfFalse, r2, _GeneratedLabel_2)
(constInt, r3, 1)
(returnWord, r3)
(goto, _GeneratedLabel_1)
(goto, _GeneratedLabel_3)
(label, _GeneratedLabel_2)
(label, _GeneratedLabel_3)
(constInt, r4, 0)
(returnWord, r4)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
