=================== IR ===================
(procBegin, main)
(constInt, r1, 1)
(constInt, r2, 1)
(addSignedWord, r3, r1, r2)
(returnWord, r3)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
(procBegin, _Global_add)
(addressOf, r4, i)
(addressOf, r5, k)
(addressOf, r6, j)
(loadWord, r7, r5)
(loadWord, r8, r6)
(addSignedWord, r9, r7, r8)
(storeWord, r4, r9)
(addressOf, r10, i)
(loadWord, r11, r10)
(returnWord, r11)
(goto, _GeneratedLabel_2)
(label, _GeneratedLabel_2)
(procEnd, _Global_add)
