=================== IR ===================
(procBegin, main)
(addressOf, r1, i)
(loadWord, r2, r1)
(constInt, r3, 1)
(subSignedWord, r4, r2, r3)
(storeWord, r1, r4)
(addressOf, r5, j)
(loadWord, r6, r5)
(constInt, r7, 1)
(addSignedWord, r8, r6, r7)
(storeWord, r5, r8)
(constInt, r9, 0)
(returnWord, r9)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
