=================== IR ===================
(procBegin, main)
(addressOf, r1, i)
(addressOf, r2, p)
(loadWord, r3, r2)
(unaryLogicalNegation, r4, r3)
(storeWord, r1, r4)
(constInt, r5, 0)
(returnWord, r5)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
