=================== IR ===================
(procBegin, main)
(addressOf, r1, i)
(addressOf, r2, p)
(addressOf, r3, j)
(loadWord, r4, r2)
(loadWord, r5, r3)
(constInt, r6, 4)
(multSignedWord, r7, r6, r5)
(addSignedWord, r8, r4, r7)
(loadWord, r9, r8)
(storeWord, r1, r9)
(constInt, r10, 0)
(returnWord, r10)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
