=================== IR ===================
(procBegin, _Global_foo)
(constInt, r1, 37)
(castWordToByte, r2, r1)
(returnByte, r2)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, _Global_foo)
(procBegin, main)
(addressOf, r3, x)
(call, _Global_foo)
(resultByte, r4)
(castSignedByteToWord, r5, r4)
(storeWord, r3, r5)
(addressOf, r6, x)
(loadWord, r7, r6)
(returnWord, r7)
(goto, _GeneratedLabel_2)
(label, _GeneratedLabel_2)
(procEnd, main)
