=================== IR ===================
(procBegin, main)
(addressOf, r1, a)
(addressOf, r2, b)
(loadWord, r3, r2)
(storeWord, r1, r3)
(addressOf, r4, a)
(constInt, r5, 56)
(storeWord, r4, r5)
(constInt, r6, 0)
(returnWord, r6)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
