=================== IR ===================
(procBegin, main)
(addressOf, r1, p)
(addressOf, r2, _StringLabel_0)
(storeWord, r1, r2)
(addressOf, r3, q)
(addressOf, r4, _StringLabel_1)
(storeWord, r3, r4)
(addressOf, r5, r)
(addressOf, r6, _StringLabel_0)
(storeWord, r5, r6)
(constInt, r7, 0)
(returnWord, r7)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
