=================== IR ===================
(procBegin, main)
(addressOf, r1, i)
(addressOf, r2, i)
(loadWord, r3, r2)
(gotoIfFalse, r3, _GeneratedLabel_2)
(addressOf, r4, i)
(loadWord, r8, r4)
(goto, _GeneratedLabel_3)
(label, _GeneratedLabel_2)
(addressOf, r6, i)
(loadWord, r8, r6)
(label, _GeneratedLabel_3)
(phi, r8, r5, r7)
(storeWord, r1, r8)
(constInt, r9, 0)
(returnWord, r9)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
