=================== IR ===================
(procBegin, main)
(label, _GeneratedLabel_2)
(addressOf, r1, i)
(constInt, r2, 1)
(loadWord, r3, r1)
(eqWord, r4, r3, r2)
(gotoIfFalse, r4, _GeneratedLabel_3)
(addressOf, r5, j)
(constInt, r6, 56)
(storeWord, r5, r6)
(goto, _GeneratedLabel_2)
(label, _GeneratedLabel_3)
(addressOf, r7, i)
(constInt, r8, 9)
(storeWord, r7, r8)
(constInt, r9, 0)
(returnWord, r9)
(goto, _GeneratedLabel_1)
(label, _GeneratedLabel_1)
(procEnd, main)
